#!/usr/bin/env bash
# This script lists the content of the current directory
# Only displays the part of the name after the first dash

for file in *
do
  # Skip hidden files
  if [[ "$file" == -* ]]; then
    continue
  fi

  # Remove everything up to the first dash
  echo "${file#*-}"
done
